### PR TITLE
Rebases 'async' branch on master

### PR DESCRIPTION
**Pull request by nakomis**
Rebased on master

### CODE REVIEW

**Comment by nakomis** [comment]
What's the status of the 'async' branch. Is it ready to merge into master any time soon?

**Comment by krujos** [comment]
I have not worked on it in awhile, I know there has been at least one broker API change since I last touched it.

**Comment by robertgmoss** [comment]
@krujos Are you talking about the parameters API? Or are you talking about a change to the Async API that this has not implemented yet? If the former, once my PR is merged this could be rebased on top?

**Comment by krujos** [comment]
I'm talking about the former, there was an API change (related to status I think, but I've not looked in awhile). I don't have any problem with a rebase.

**Comment by scottfrederick** [comment]
After merging this rebase PR, master is still ahead of this branch due to the parameters API changes made on master. Instead of rebasing master again, we could merge this async branch onto master and go from there. It appears that the async and parameters API support is backward compatible WRT the service broker API, so merging would appear to be safe. 

Thoughts @spgreenberg @krujos @nakomis @robertgmoss?

**Comment by spgreenberg** [comment]
Ok with me.  I typically make all changes on a version branch and merge the
latest version into master.

**Comment by scottfrederick** [comment]
@nakomis I was looking at the history now, and looking at re-basing again on the latest master. When doing this, git wants to pull all your rebased changes in again. How did you do your rebase that I merged with this PR? Did you do `git checkout async; get rebase -i master` or something different?

**Pull request merged**
