### PR TITLE
Parameters

### PR DESCRIPTION
**Pull request by robertgmoss**
Add support for users to send service-specific configuration parameters along with provision, update and bind requests as per v2.5

### CODE REVIEW

**Comment by scottfrederick** [comment]
@robertgmoss Thanks for adding the arbitrary parameter support. This is a nice CF feature, and a few of have service brokers that need to use this. 

I'm curious how you are using the new `getParameters()` methods. 

```
public <T> T getParameters(Class<T> cls) {
+        ObjectMapper mapper = new ObjectMapper();
+        return mapper.convertValue(parameters, cls);
+    }
```

It looks like your broker has domain classes that you pass into `getParameters()`, and you let Jackson map the json to your domain class. What happens when the json that the end user constructed doesn't match your domain object? It seems likely that a broker would get exceptions thrown from Jackson that it would need to handle when using this code, since it can't enforce that the end user provide well-formed json or json that matches what the broker expects. Is that what you are doing in your broker(s)?

Another option would be to have Jackson map the parameters to a `Map<Object, Object>` and let the implementing brokers validate the Map contents as they see fit. What thoughts to you have on that implementation?

**Comment by robertgmoss** [comment]
You are correct, any exceptions would need to be handled by the Broker - I wrote these as a convenience, but perhaps it would be better to throw a checked exception to force this case to be dealt with?

Another method that just returns a `Map<Object, Object>` might be preferred by some people, so I'd be happy to include that.

**Comment by scottfrederick** [comment]
Personally, I hate checked exceptions. I'd actually like to change the exceptions currently in this project to be unchecked in a future release. The Spring framework in general avoids checked exceptions, and this project should also. 

That said, catching the Jackson-specific exceptions and throwing a known exception is a good idea. Just throwing `IllegalArgumentException` might be sufficient.

Leaving the typed `getParameters()` methods you already have and adding another that returns `Map` is a good idea too - giving users the choice of how they want to handle mapping of parameters.

**Comment by robertgmoss** [comment]
@scottfrederick I quite agree about exceptions in general, but that this is a special case, so have done as you have suggested.  Have also added the default `getParameters()` that returns a `Map`.

**Comment by robertgmoss** [comment]
can this be merged?

**Comment by nota-ja** [comment]
I also have been waiting this p-r to be merged. Is there another problem?

**Comment by scottfrederick** [comment]
@robertgmoss I merged this PR and then did more work on master: https://github.com/cloudfoundry-community/spring-boot-cf-service-broker/commit/dbcb794e7320a872953542af6d64e1fb24452b6a. 

I added testing that the parameters would get marshalled and unmarshalled in the integration tests. I also made changes to the way the parameters are modeled in the request classes to get away from storing as an `Object` there. Can you test these changes and make sure the work for you?

**Pull request merged**
